# -*- coding: utf-8 -*-
"""Exercise 15 - Reverse Word Order

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--n1-ISYQLBpEEszddKU7z7PLIOKlW99
"""

def msg_reverse(msg):
  msg_list = msg.split(' ')
  return " ".join(msg_list[::-1])


message = input('Message: ')
print(msg_reverse(message))