# -*- coding: utf-8 -*-
"""Exercise 24 - Draw a game board

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-SKz1jZbBskEg9fh7CxyDUVGbhX7j1Cw
"""

# Game board

def create_board(x, y):
  if (x and y) > 0:
    for i in range(y):
      print(' ---' * x)
      print('|   ' * (x) + '|')
    print(' ---' * x)
  else:
     print('Board size too small')


size = tuple(input('Size (x,y) ').split(', '))
x, y = int(size[0]), int(size[1])

create_board(x, y)