# -*- coding: utf-8 -*-
"""Exercise 18 - Cows and Bulls

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KzeaxVVJiQuTAcpwO3g1zvEUM38ki0uR
"""

import random

print('Cows & Bulls Game\n')

def cows_bulls(guess, actual):
  guess, actual = str(guess), str(actual)
  matches = 0
  for char in range(0, 4):
    if guess[char] == actual[char]:
      matches += 1
  return matches

actual = random.randint(1000, 9999)

cows = 0
tries = 0

while cows != 4:
  guess = input('Enter your guess: ')
  cows = cows_bulls(guess, actual)
  print(f'Cows: {cows} Bulls: {4 - cows}\n')
  tries += 1

print(f'Congratulations, you got it! It took you {tries} tries!')