# -*- coding: utf-8 -*-
"""Exercise 1 - Character Input

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Q0Hxqzq8AD5GbdD3ycYfEtKWYrJ7L8v
"""

import datetime

name = input('What is your name? ')
age = int(input('What is your age? '))
current_year = 2020 # A better way would be to use datetime module to get the current year, but for this exercise it will just be hard-coded in
c_year = 2020 + (100 - age)
print(f'You will turn 100 in the year {c_year}')