# -*- coding: utf-8 -*-
"""Exercise 27 - Tic Tac Toe Draw

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v0FwciXfxx_AH2DelejN8Wjduh7KdDKt
"""

# Tic Tac Toe Draw
game = [[0, 0, 0], 
        [0, 0, 0], 
        [0, 0, 0]]

X_playing = True # X goes first
O_playing = False

def place(A, who_playing):
  new_A = tuple(input(f'Where should {A} go? (row, col.) ').split(', '))
  A_row, A_col = int(new_A[0]), int(new_A[1])
  if game[A_row - 1][A_col - 1] == 0:
    game[A_row - 1][A_col - 1] = A
    print(game)
    return False, True # player, opponent
  else:
    print('That spot is already taken, try again')
    return True, False # player, opponent


while any(0 in sub for sub in game): # Only if space remains in matrix
  while X_playing:
    X_playing, O_playing = place('X', X_playing)

  if any(0 in sub for sub in game): # For last turn where O has no space
    while O_playing:
      O_playing, X_playing = place('O', O_playing)

print('Game over')