# -*- coding: utf-8 -*-
"""Exercise 11 - Fun with Primes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FAe2R5ZDYuyVz3t3T1vdU-wL7_QkGenT
"""

# Prime Check Function
def is_prime(n):
  if n <= 1:
    return False
  for i in range(2, n):
    if n % i == 0:
      return False
      break
  return True
  

print(is_prime(10230))

# First n primes
N = int(input('First n primes: '))

count = 0
number = 2

while count != N:
  if is_prime(number):
    print(number)
    count += 1
  number += 1

# Prime Factorization (WIP)
def p_factor(n):
  if is_prime(n):
    return n
  else:
    factors = []
    for number in range(n):
    return factors