# -*- coding: utf-8 -*-
"""Exercise 33-36 Birthday Dictionaries

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QntSAPiT0d3BXKoak9BsleIkxHF14cA6
"""

# Exercise 33
birthdays = {
    'Albert Einstein':'1879-03-14',
    'Benjamin Franklein':'1706-01-17',
    'Ada Lovelace':'1815-12-10'
}

print('Welcome to the Birthday Dictionary. We know the birthdays of:')
for person in birthdays.keys(): print(person)

person = input("Who's birthday do you want to look up? ")

if person in birthdays.keys():
  print(f"{person}'s birthday is {birthdays[person]}")
else: 
  print(f"Sorry we do not have {person}'s birthday")

# Exercise 34
import json
import time

json_path = 'birthdays.json'

# Reading JSON
with open(json_path, "r") as f:
    birthdays = json.load(f)


def lookup():
  person = input("Whose birthday do you want to look up? ")
  if person in birthdays.keys():
    print(f"{person}'s birthday is {birthdays[person]}")
  else: 
    print(f"Sorry we do not have {person}'s birthday")


def new_birthday():
  name = input('What is the name of the person? (First Last) ')
  birthday = input('What is their birthday? (YYYY-MM-DD) ')
  print(f"{name}'s birthday has successfully been added.")
  birthdays[name] = birthday
  return birthdays


def remove():
  name = input('Whose birthday would you like to remove? ')
  if name in birthdays.keys():
    del birthdays[name]
    print(f"Successfully removed {name}'s birthday")
  else:
    print(f"Sorry, it seems like we don't have {name}'s birthday")
  return birthdays


print('Welcome to the Birthday Dictionary. We know the birthdays of:')
for person in birthdays.keys(): print(person)

action = ""
while True:
  action = input('What would you like to do? (LOOKUP, ADD, REMOVE, QUIT) ')
  if action.upper() == "QUIT":
    break
  elif action.upper() == "LOOKUP":
    lookup()
  elif action.upper() == "ADD":
    new_birthday()
  elif action.upper() == "REMOVE":
    remove()
  else:
    print('Sorry that is not a supported command, try again')

print('Saving...')

# Saving JSON
with open(json_path, "w") as f:
  json.dump(birthdays, f)

time.sleep(1)

print('Saved.')

!pip install collections

# Exercise 35
from collections import Counter

months = []
m_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

for person in birthdays.keys():
  month = birthdays[person][5:7]
  m_name = m_names[(int(month) - 1)]
  months.append(m_name)

count = Counter(months)

print(count)

# Exercise 36
from bokeh.plotting import figure, show, output_file
output_file('birthdays.json')

x = list(count.keys())
y = list(count.values())

p = figure(x_range = m_names)
p.vbar(x = x, top = y, width = 0.5)

show(p)