# -*- coding: utf-8 -*-
"""Exercise 26 - Check Tic Tac Toe

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v3_m-GkNKe9xfTeTrEOhMy7zRMohknt1
"""

# Check Tic Tac Toe
game = [[0, 0, 0], 
        [0, 0, 0], 
        [0, 0, 0]]

players = [1, 2]


def h_check(game): # Horizontal check
  for player in players:
    for i in range(0,3):
      if game[i][0] == game[i][1] == game[i][2] == player:
        return f'{player} won with horizontal'


def v_check(game): # Vertical check
  for player in players:
    for i in range(0,3):
      if game[0][i] == game[1][i] == game[2][i] == player:
        return f'{player} won with vertical'


def d_check(game):
  for player in players:
    if game[0][0] == game[1][1] == game[2][2] == player:
          return f'{player} won with diagonal'
    elif game[0][2] == game[1][1] == game[2][0] == player:
          return f'{player} won with diagonal'

print(h_check(game))
print(v_check(game))
print(d_check(game))