# -*- coding: utf-8 -*-
"""FizzBuzz

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RrgOtDke8IhcdfIcjYSvOMdIpc_pqABp
"""

def fizz_buzz(input):
  if (input % 5 == 0) and (input % 3 == 0):
    return 'FizzBuzz'
  if input % 5 == 0:
    return 'Buzz'
  if input % 3 == 0:
    return "Fizz"
  return input


print(fizz_buzz(15))